services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/app
        command: ['npm', 'run', 'dev']
        ports:
            - 3000:3000
        networks:
            - internal
        depends_on:
            - proxy
    proxy:
        build:
            context: .
            dockerfile: Dockerfile.caddy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            internal:
                aliases:
                    - www.michalmatus.space
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
networks:
    internal:
